---
- name: Copy cleanup_script.sh to the target host
  copy:
    src: cleanup_script.sh
    dest: /usr/local/bin/cleanup_script.sh
    mode: 'u=rwx,g=r,o=r'

- name: Schedule the cleanup task using cron
  cron:
    name: Cleanup Task
    job: "/usr/local/bin/cleanup_script.sh"
    minute: "0"
    hour: "4"  # Adjust the desired hour (0-23) for the cleanup task
    user: root
    state: present
